# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 376)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_input = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_input.setObjectName("label_input")
        self.verticalLayout_4.addWidget(self.label_input)
        self.input_file_edit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.input_file_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.input_file_edit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.input_file_edit.setObjectName("input_file_edit")
        self.verticalLayout_4.addWidget(self.input_file_edit)
        self.hl_browse = QtWidgets.QHBoxLayout()
        self.hl_browse.setObjectName("hl_browse")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hl_browse.addItem(spacerItem)
        self.browse_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.browse_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.browse_button.setObjectName("browse_button")
        self.hl_browse.addWidget(self.browse_button)
        self.verticalLayout_4.addLayout(self.hl_browse)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_suffix = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_suffix.setObjectName("label_suffix")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_suffix)
        self.output_suffix_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_suffix_edit.setObjectName("output_suffix_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.output_suffix_edit)
        self.label_r = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_r.setObjectName("label_r")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_r)
        self.r_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.r_edit.setObjectName("r_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.r_edit)
        self.label_offset = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_offset.setObjectName("label_offset")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_offset)
        self.offset_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.offset_edit.setObjectName("offset_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.offset_edit)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quit_button.setObjectName("quit_button")
        self.horizontalLayout.addWidget(self.quit_button)
        self.generate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate_button.setObjectName("generate_button")
        self.horizontalLayout.addWidget(self.generate_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.plot_widget = PlotWidget(parent=self.centralwidget)
        self.plot_widget.setObjectName("plot_widget")
        self.horizontalLayout_2.addWidget(self.plot_widget)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Path Interpolator-Surat Layek"))
        self.label_input.setText(_translate("MainWindow", "Input File:"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.label_suffix.setText(_translate("MainWindow", "Output File Number/Suffix:"))
        self.output_suffix_edit.setText(_translate("MainWindow", "1"))
        self.label_r.setText(_translate("MainWindow", "Spacing:"))
        self.r_edit.setText(_translate("MainWindow", "0.001"))
        self.label_offset.setText(_translate("MainWindow", "Offset:"))
        self.offset_edit.setText(_translate("MainWindow", "0.001"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.generate_button.setText(_translate("MainWindow", "Generate Points"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
